

title: "Saanvi S. Subramanian"
description: "<strong>Computation and Neural Systems student at Caltech</strong>"

# Optional: include social links
author:
  name: "Saanvi Skanda Subramanian"
  email: "ssubramanian@caltech.edu"
  github: "saanviiyer"
