title: Saanvi S. Subramanian
email: ssubramanian@caltech.edu
description: >-
  Saanvi S. Subramanian uses machine learning to study biological intelligence
  and interventions that can improve health.
baseurl: ""      # e.g. "/mysite" if hosted at a subpath, else leave blank
url: "https://saanviiyer.github.io"

# Markdown / build settings
markdown: kramdown
permalink: pretty
exclude:
  - README.md

defaults:
  - scope:
      path: ""
    values:
      layout: default
