/* Glossary: every term in plain language. Keys are referenced by TD.g(key) across the modules. */
(function () {
  'use strict';
  const G = {
    plaintext: ['Plaintext', 'The readable message before encryption.'],
    ciphertext: ['Ciphertext', 'The scrambled output of encryption. It should look like noise to anyone without the key.'],
    key: ['Key', 'A piece of secret (or public) information that controls what an algorithm does. Same algorithm, different key, different result.'],
    symmetric: ['Symmetric encryption', 'Encryption where the same key locks and unlocks. Both sides must already share it. AES is symmetric.'],
    asymmetric: ['Public-key (asymmetric) cryptography', 'Encryption with two keys: a public one anyone may use and a private one only the owner holds. RSA, ElGamal and elliptic-curve schemes are asymmetric.'],
    publickey: ['Public key', 'The half of a key pair you publish. Others use it to encrypt messages to you or to check your signatures.'],
    privatekey: ['Private key', 'The half of a key pair you keep secret. It decrypts messages sent to you and creates your signatures.'],
    oneway: ['One-way function', 'A calculation that is fast to do and extremely slow to undo. Multiplying primes is easy, factoring the product is hard.'],
    trapdoor: ['Trapdoor function', 'A one-way function with a secret shortcut. Without the secret, undoing it is hopeless. With it, undoing it is easy. RSA is the classic example, and its trapdoor is knowing p and q.'],
    prime: ['Prime number', 'A whole number above 1 whose only divisors are 1 and itself, like 2, 3, 5, 7, 11.'],
    trial: ['Trial division', 'The simplest primality test and factoring method: try dividing by 2, 3, 5, 7 and so on up to the square root.'],
    factoring: ['Factoring', 'Breaking a number into the primes that multiply to give it, for example 3233 = 61 × 53. For numbers with hundreds of digits, no fast method is known.'],
    modular: ['Modular arithmetic', 'Arithmetic on a clock. "a mod n" is the remainder after dividing a by n, so results always land between 0 and n − 1. For example 17 mod 5 = 2.'],
    modulus: ['Modulus', 'The number you divide by in modular arithmetic, the size of the clock. In RSA it is n = p × q.'],
    congruent: ['Congruent (≡)', 'Two numbers are congruent mod n when they leave the same remainder. 17 ≡ 2 (mod 5).'],
    gcd: ['Greatest common divisor (gcd)', 'The largest number that divides both of two numbers. gcd(12, 18) = 6.'],
    coprime: ['Coprime', 'Two numbers are coprime when their gcd is 1, meaning they share no factor except 1. 8 and 15 are coprime.'],
    euclid: ['Euclidean algorithm', 'A fast way to find a gcd: divide, keep the remainder, then divide the old divisor by that remainder. Repeat until the remainder is 0. The last nonzero remainder is the gcd.'],
    egcd: ['Extended Euclidean algorithm', 'The Euclidean algorithm plus bookkeeping. It also finds whole numbers s and t with s·a + t·b = gcd(a, b). That is how modular inverses are computed.'],
    inverse: ['Modular inverse', 'The number that undoes multiplication mod n. The inverse of 3 mod 7 is 5, because 3 × 5 = 15 = 2 × 7 + 1. It exists only when the number is coprime to n.'],
    totient: ['Euler\'s totient φ(n)', 'How many numbers from 1 to n share no factor with n. For n = p × q with distinct primes, φ(n) = (p − 1)(q − 1).'],
    euler: ['Euler\'s theorem', 'If m shares no factor with n, then m raised to the power φ(n) leaves remainder 1 mod n. It is the reason RSA decryption undoes encryption.'],
    fermat: ['Fermat\'s little theorem', 'The prime special case of Euler\'s theorem: for a prime p and any m not divisible by p, m^(p−1) ≡ 1 mod p.'],
    crt: ['Chinese remainder theorem', 'If you know a number\'s remainders mod several coprime moduli, you can rebuild its remainder mod their product. Used in RSA proofs, speed-ups and attacks.'],
    modexp: ['Modular exponentiation', 'Computing a^b mod n. Done well, it takes about two multiplications per bit of b, even when b has hundreds of digits.'],
    sqmul: ['Square-and-multiply', 'The standard way to do modular exponentiation. Walk through the exponent\'s bits, squaring at each bit and multiplying by the base when the bit is 1.'],
    encoding: ['Encoding (ASCII)', 'A fixed public mapping from characters to numbers, such as A = 65 and a = 97. It is not encryption, anyone can reverse it.'],
    block: ['Block', 'A fixed-size chunk of the message that is encrypted as one unit. In RSA each block must be a number smaller than n.'],
    textbook: ['Textbook RSA', 'RSA exactly as in the formulas, with no padding. It is deterministic and malleable, so it is unsafe in practice.'],
    padding: ['Padding', 'Extra bytes added to a message before encryption or signing. In RSA, good padding adds randomness and structure that block many attacks.'],
    oaep: ['OAEP', 'Optimal Asymmetric Encryption Padding, the standard randomized padding for RSA encryption. The same message encrypts differently every time.'],
    pss: ['PSS', 'Probabilistic Signature Scheme, the modern padding for RSA signatures.'],
    deterministic: ['Deterministic encryption', 'Encryption where the same message and key always give the same ciphertext. It leaks when messages repeat.'],
    dh: ['Diffie-Hellman', 'A method for two parties to agree on a shared secret over a public channel, published in 1976.'],
    dlog: ['Discrete logarithm', 'Given g, p and A = g^a mod p, find a. Believed to be hard for large, well-chosen p. Diffie-Hellman and ElGamal rely on it.'],
    generator: ['Generator', 'A base g whose powers g, g², g³, … mod p run through many (ideally all) of the possible values.'],
    primitive: ['Primitive root', 'A generator mod a prime p whose powers hit every number from 1 to p − 1.'],
    order: ['Order', 'How many times you must apply an operation to an element before returning to the start. The order of 2 mod 7 is 3, because 2³ = 8 ≡ 1.'],
    mitm: ['Man-in-the-middle', 'An attacker who sits between two parties and impersonates each to the other. Plain Diffie-Hellman needs authentication, such as signatures, to stop this.'],
    elgamal: ['ElGamal encryption', 'Public-key encryption built on Diffie-Hellman. Each message gets a fresh one-time secret, so encryption is randomized.'],
    ephemeral: ['Ephemeral key (nonce)', 'A random value used once for a single operation. In ElGamal it is k. Reusing it is a serious mistake.'],
    ec: ['Elliptic curve', 'The set of points (x, y) that satisfy y² = x³ + ax + b, plus a special point at infinity. Points can be added to each other.'],
    finitefield: ['Finite field', 'A finite set of numbers where you can add, subtract, multiply and divide (except by 0). The integers mod a prime p form one.'],
    infinity: ['Point at infinity (O)', 'The zero of elliptic curve addition. P + O = P, and a point plus its mirror image gives O.'],
    scalar: ['Scalar multiplication', 'Adding a point to itself k times: kP = P + P + … + P. Fast with double-and-add, hard to undo.'],
    ecdh: ['ECDH', 'Diffie-Hellman done with elliptic curve points instead of powers mod p. Smaller keys give the same security.'],
    aes: ['AES', 'The Advanced Encryption Standard, a symmetric block cipher on 16-byte blocks, standardized in 2001. AES-128 uses a 16-byte key and 10 rounds.'],
    blockcipher: ['Block cipher', 'A symmetric cipher that scrambles one fixed-size block at a time under a key.'],
    round: ['Round', 'One pass of the same set of scrambling steps. Ciphers repeat rounds so that small effects compound.'],
    roundkey: ['Round key', 'A 16-byte key derived from the main key for one round of AES.'],
    keyschedule: ['Key schedule', 'The procedure that expands the main key into all the round keys.'],
    state: ['State', 'The 16 bytes that AES is currently working on, arranged in a 4 × 4 grid filled column by column.'],
    sbox: ['S-box', 'A fixed lookup table that substitutes one byte for another. In AES it is built from inverses in GF(2⁸) followed by a fixed bit shuffle.'],
    subbytes: ['SubBytes', 'The AES step that replaces each byte using the S-box.'],
    shiftrows: ['ShiftRows', 'The AES step that rotates row r of the state left by r positions.'],
    mixcolumns: ['MixColumns', 'The AES step that multiplies each column by a fixed matrix in GF(2⁸), so every output byte depends on all four input bytes of its column.'],
    addroundkey: ['AddRoundKey', 'The AES step that XORs the state with the round key.'],
    gf256: ['GF(2⁸)', 'A finite field with 256 elements, one per byte value. Addition is XOR, and multiplication is polynomial multiplication reduced by x⁸ + x⁴ + x³ + x + 1.'],
    xor: ['XOR (⊕)', 'Exclusive or, bit by bit: 1 when the bits differ, 0 when they match. XORing with the same value twice gives back the original.'],
    mode: ['Mode of operation', 'A rule for using a block cipher on messages longer than one block, such as GCM or CTR. Encrypting each block separately (ECB) leaks patterns.'],
    hash: ['Hash function', 'A function that turns any input into a short fixed-size fingerprint. Good ones are one-way and collision resistant.'],
    sha256: ['SHA-256', 'A widely used hash function with a 256-bit output, published by NIST in 2001.'],
    avalanche: ['Avalanche effect', 'A tiny change in the input flips about half of the output bits, in a pattern that looks random.'],
    collision: ['Collision', 'Two different inputs with the same hash. They must exist, but for a good hash nobody can find one.'],
    preimage: ['Preimage', 'An input that produces a given hash. Finding one should take about 2^256 tries for SHA-256.'],
    birthday: ['Birthday bound', 'Among about √N random values from N possibilities, two are likely to match. So collisions in a b-bit hash appear after about 2^(b/2) tries.'],
    signature: ['Digital signature', 'A value only the private key holder can produce for a message, but anyone with the public key can check. It proves origin and that the message was not changed.'],
    verify: ['Verification', 'Checking a signature with the public key. It either matches the message exactly or fails.'],
    bruteforce: ['Brute force', 'Trying every possibility until one works. The goal of key sizes is to make this take far longer than anyone can afford.'],
    gnfs: ['General number field sieve', 'The fastest known classical algorithm for factoring large numbers. Its running time grows a bit slower than exponentially in the number of digits.'],
    fermatfact: ['Fermat factorization', 'Writing n as a² − b² = (a − b)(a + b). It finds the factors almost instantly when p and q are close together.'],
    commonmod: ['Common modulus attack', 'If the same message is encrypted under the same n with two coprime exponents, an eavesdropper can recover it without any private key.'],
    hastad: ['Håstad\'s broadcast attack', 'If the same unpadded message is sent with e = 3 to three people, an eavesdropper can combine the ciphertexts and take a cube root.'],
    securitybits: ['Security level (bits)', 'A way to compare strengths: k-bit security means the best known attack takes about 2^k operations. 128 bits is a common target.'],
    shor: ['Shor\'s algorithm', 'A quantum algorithm that factors and solves discrete logarithms efficiently. It would break RSA, Diffie-Hellman and elliptic curves, but needs a large fault-tolerant quantum computer that does not exist yet.'],
    probprime: ['Probable prime test', 'A fast randomized primality test such as Miller-Rabin. Each round that passes makes "composite" less likely, and dozens of rounds leave a negligible chance of error.'],
  };
  for (const [k, [term, def]] of Object.entries(G)) TD.GLOSSARY[k] = { term, def };
})();
